name: Deploy to Kubernetes

on:
  workflow_call: # Add this trigger to make the workflow reusable
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      KUBECONFIG:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify Dockerfile and deployment.yaml
        run: |
          ls
          if [ ! -f Dockerfile ] && [ ! -f dockerfile ]; then
            echo "Error: Dockerfile is missing in the root directory."
            exit 1
          fi
          if [ ! -f deployment.yaml ]; then
            echo "Error: deployment.yaml is missing in the root directory."
            exit 1
          fi
          echo "Required files are present: Dockerfile/dockerfile and deployment.yaml."
          echo "Both Dockerfile and deployment.yaml are present."

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2


      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Step 5: Configure Kubernetes credentials
      - name: Configure Kubernetes credentials
        uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      # Step 6: Build and push Docker image
      - name: Build and push Docker image
        run: |
          REPO_NAME=$(basename "$PWD")
          echo "Building Docker image for $REPO_NAME"
          docker build -t keanuwatts/theclusterflux:$REPO_NAME .

          echo "Pushing Docker image for $REPO_NAME"
          docker push keanuwatts/theclusterflux:$REPO_NAME

      # Step 7: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          echo "Deploying to Kubernetes using dynamically generated deployment.yaml"
          kubectl apply -f deployment.yaml
          