name: Deploy to Kubernetes

on:
  workflow_call: # Add this trigger to make the workflow reusable
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      KUBECONFIG:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify Dockerfile and deployment.yaml
        run: |
          ls
          if [ ! -f Dockerfile ] && [ ! -f dockerfile ]; then
            echo "Error: Dockerfile is missing in the root directory."
            exit 1
          fi
          if [ ! -f deployment.yaml ]; then
            echo "Error: deployment.yaml is missing in the root directory."
            exit 1
          fi
          echo "Both Dockerfile and deployment.yaml are present."

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure Kubernetes credentials
        uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Build and push Docker image
        run: |
          REPO_NAME=$(basename "$PWD")
          echo "Building Docker image for $REPO_NAME"
          docker build -t keanuwatts/theclusterflux:$REPO_NAME .

          echo "Pushing Docker image for $REPO_NAME"
          docker push keanuwatts/theclusterflux:$REPO_NAME

      - name: Deploy to Kubernetes
        run: |
          echo "Deploying to Kubernetes using dynamically generated deployment.yaml"
          kubectl apply -f deployment.yaml
      
          # Extract deployment names from deployment.yaml
          DEPLOYMENT_NAMES=$(yq -r '. | select(.kind == "Deployment") | .metadata.name' deployment.yaml)
      
          if [ -z "$DEPLOYMENT_NAMES" ]; then
            echo "No deployments found in deployment.yaml."
            exit 1
          fi
      
          # Restart each deployment
          for DEPLOYMENT in $DEPLOYMENT_NAMES; do
            echo "Restarting deployment: $DEPLOYMENT"
            kubectl rollout restart deployment "$DEPLOYMENT"
          done